// Code generated by packages/contracts-codegen/generate.ts from contracts/events/v1. DO NOT EDIT.

// Package events contains Go bindings for the versioned AnvilKit platform
// event contracts (contracts/events/v1). The JSON Schema files are the
// contract of record; this package is generated from them and committed so
// the worker repo builds standalone. Platform CI regenerates and fails on
// drift. Contracts evolve additively only (FR-002, ADR-001).
package events

// Event type discriminators.
const (
	EventTypeExportRequested = "deployment.export.requested"
	EventTypeArtifactReady   = "deployment.artifact.ready"
	EventTypeExportFailed    = "deployment.export.failed"
)

// RenderMode identifies the render strategy driver (PRD 0010 §6.3). fetch_route is the MVP mode; react_ssr and html_export are deferred.
type RenderMode string

// RenderMode values.
const (
	RenderModeFetchRoute RenderMode = "fetch_route"
	RenderModeReactSsr   RenderMode = "react_ssr"
	RenderModeHtmlExport RenderMode = "html_export"
)

// Environment is the deployment environment (PRD 0010 §6.3).
type Environment string

// Environment values.
const (
	EnvironmentProduction Environment = "production"
	EnvironmentPreview    Environment = "preview"
)

// ErrorClassification is the retry classification of an error code (PRD 0010 §13): RETRYABLE errors back off and retry up to maxRetries = 3, NON_RETRYABLE errors fail the deployment immediately.
type ErrorClassification string

// ErrorClassification values.
const (
	ErrorClassificationRetryable    ErrorClassification = "RETRYABLE"
	ErrorClassificationNonRetryable ErrorClassification = "NON_RETRYABLE"
)

// FailedStage is the pipeline stage that failed — the trace-span vocabulary of PRD 0010 §15.3.
type FailedStage string

// FailedStage values.
const (
	FailedStageConsumeJob            FailedStage = "consume_job"
	FailedStageLoadDeployment        FailedStage = "load_deployment"
	FailedStageAcquireLock           FailedStage = "acquire_lock"
	FailedStageUpdateStatusExporting FailedStage = "update_status_exporting"
	FailedStageRenderHtml            FailedStage = "render_html"
	FailedStageHarvestDependencies   FailedStage = "harvest_dependencies"
	FailedStageUploadArtifacts       FailedStage = "upload_artifacts"
	FailedStageWriteManifest         FailedStage = "write_manifest"
	FailedStageSubmitArtifact        FailedStage = "submit_artifact"
	FailedStageUpdateStatusReady     FailedStage = "update_status_ready"
	FailedStageEmitReady             FailedStage = "emit_ready"
	FailedStageAckMessage            FailedStage = "ack_message"
)

// ErrorCode is a job-level error classification (full PRD 0010 §13 registry). New codes require a contracts version note.
type ErrorCode string

// ErrorCode values.
const (
	ErrorCodeValidationFailed                 ErrorCode = "VALIDATION_FAILED"
	ErrorCodePageNotFound                     ErrorCode = "PAGE_NOT_FOUND"
	ErrorCodeVersionNotFound                  ErrorCode = "VERSION_NOT_FOUND"
	ErrorCodeVersionSlugMismatch              ErrorCode = "VERSION_SLUG_MISMATCH"
	ErrorCodePageNotPublished                 ErrorCode = "PAGE_NOT_PUBLISHED"
	ErrorCodeInvalidSlug                      ErrorCode = "INVALID_SLUG"
	ErrorCodeAssetPermissionDenied            ErrorCode = "ASSET_PERMISSION_DENIED"
	ErrorCodeUnresolvedAssetRef               ErrorCode = "UNRESOLVED_ASSET_REF"
	ErrorCodeUnsupportedDynamicImageOptimizer ErrorCode = "UNSUPPORTED_DYNAMIC_IMAGE_OPTIMIZER"
	ErrorCodePathTraversalDetected            ErrorCode = "PATH_TRAVERSAL_DETECTED"
	ErrorCodeRenderOrigin401                  ErrorCode = "RENDER_ORIGIN_401"
	ErrorCodeRenderOrigin403                  ErrorCode = "RENDER_ORIGIN_403"
	ErrorCodeRenderOrigin404                  ErrorCode = "RENDER_ORIGIN_404"
	ErrorCodeRenderOrigin5xx                  ErrorCode = "RENDER_ORIGIN_5XX"
	ErrorCodeRenderOriginTimeout              ErrorCode = "RENDER_ORIGIN_TIMEOUT"
	ErrorCodeStorageTimeout                   ErrorCode = "STORAGE_TIMEOUT"
	ErrorCodeStorage5xx                       ErrorCode = "STORAGE_5XX"
	ErrorCodeArtifactUploadTimeout            ErrorCode = "ARTIFACT_UPLOAD_TIMEOUT"
	ErrorCodeDeploymentServiceTimeout         ErrorCode = "DEPLOYMENT_SERVICE_TIMEOUT"
	ErrorCodeQueueTemporaryFailure            ErrorCode = "QUEUE_TEMPORARY_FAILURE"
	ErrorCodeStatusConflict                   ErrorCode = "STATUS_CONFLICT"
	ErrorCodeConfigMissing                    ErrorCode = "CONFIG_MISSING"
	ErrorCodeDeploymentService401             ErrorCode = "DEPLOYMENT_SERVICE_401"
	ErrorCodeDeploymentService403             ErrorCode = "DEPLOYMENT_SERVICE_403"
	ErrorCodeAssetService401                  ErrorCode = "ASSET_SERVICE_401"
	ErrorCodeAssetService403                  ErrorCode = "ASSET_SERVICE_403"
)

// ExportRequested is the inbound event deployment.export.requested (PRD 0008 §8.1). Event fields renderMode/version/slug are hints reconciled against the authoritative deployment record (FR-004).
type ExportRequested struct {
	// EventID: Event ID
	EventID string `json:"eventId"`
	// EventType: Always deployment.export.requested
	EventType string `json:"eventType"`
	// DeploymentID: Deployment record ID — the authoritative idempotency anchor (one deploymentId → at most one artifact manifest)
	DeploymentID string `json:"deploymentId"`
	// TeamID: Team ID
	TeamID string `json:"teamId"`
	// SiteID: Site ID
	SiteID string `json:"siteId"`
	// PageID: Page ID
	PageID string `json:"pageId"`
	// Slug: Page path
	Slug string `json:"slug"`
	// Version: Published version — must be pinned at render (PRD 0008 §12.1 / FR-004)
	Version string `json:"version"`
	// RenderMode: Render mode; fetch_route is the MVP mode, react_ssr and html_export are deferred
	RenderMode RenderMode `json:"renderMode"`
	// TargetID: CDN target ID (passed through to downstream)
	TargetID string `json:"targetId"`
	// Environment: Deployment environment
	Environment Environment `json:"environment"`
	// RequestedBy: Requesting user, for auditing (optional)
	RequestedBy string `json:"requestedBy,omitempty"`
	// IdempotencyKey: Producer-supplied queue-dedup hint only; the worker derives its own artifact key from deploymentId (PRD 0008 §12)
	IdempotencyKey string `json:"idempotencyKey"`
	// CreatedAt: Emit time, ISO 8601 (optional)
	CreatedAt string `json:"createdAt,omitempty"`
}

// ArtifactReady is the outbound event deployment.artifact.ready (PRD 0010 §10.3.2; routes[] intentionally omitted per ADR-001). Emitted only after the CAS transition to ARTIFACT_READY succeeds (FR-013).
type ArtifactReady struct {
	// SchemaVersion: Outbound event schema version
	SchemaVersion int64 `json:"schemaVersion"`
	// EventID: Event ID
	EventID string `json:"eventId"`
	// EventType: Always deployment.artifact.ready
	EventType string `json:"eventType"`
	// DeploymentID: Deployment record ID — consumer dedup key
	DeploymentID string `json:"deploymentId"`
	// TeamID: Team ID
	TeamID string `json:"teamId"`
	// SiteID: Site ID
	SiteID string `json:"siteId"`
	// PageID: Page ID
	PageID string `json:"pageId"`
	// Slug: Page path
	Slug string `json:"slug"`
	// Version: Published version the artifact was rendered from
	Version string `json:"version"`
	// Environment: Deployment environment
	Environment Environment `json:"environment"`
	// RenderMode: Render mode used to produce the artifact
	RenderMode RenderMode `json:"renderMode"`
	// ArtifactBasePath: Storage base path of the artifact, confined to sites/{siteId}/deployments/{deploymentId} (FR-010)
	ArtifactBasePath string `json:"artifactBasePath"`
	// ManifestStorageKey: Storage key of artifact-manifest.json (internal-only object, never public — FR-012)
	ManifestStorageKey string `json:"manifestStorageKey"`
	// ManifestDigest: SHA-256 digest of the manifest, sha256-<hex> form
	ManifestDigest string `json:"manifestDigest"`
	// Entry: Entry HTML path within the artifact, e.g. /home/index.html
	Entry string `json:"entry"`
	// FilesCount: Number of files in the artifact
	FilesCount int64 `json:"filesCount"`
	// TotalBytes: Total artifact size in bytes
	TotalBytes int64 `json:"totalBytes"`
	// TraceID: Trace ID of the producing job (cross-boundary traceability, FR-020)
	TraceID string `json:"traceId"`
	// CreatedAt: Emit time, ISO 8601 — field name matches the inbound event vocabulary (PRD 0008 §8.1)
	CreatedAt string `json:"createdAt"`
}

// ExportFailed is the outbound event deployment.export.failed (PRD 0010 §10.3.2). Emitted with the final classified error code after the CAS transition to EXPORT_FAILED (FR-013, FR-014).
type ExportFailed struct {
	// SchemaVersion: Outbound event schema version
	SchemaVersion int64 `json:"schemaVersion"`
	// EventID: Event ID
	EventID string `json:"eventId"`
	// EventType: Always deployment.export.failed
	EventType string `json:"eventType"`
	// DeploymentID: Deployment record ID — consumer dedup key
	DeploymentID string `json:"deploymentId"`
	// TeamID: Team ID
	TeamID string `json:"teamId"`
	// SiteID: Site ID
	SiteID string `json:"siteId"`
	// PageID: Page ID
	PageID string `json:"pageId"`
	// Slug: Page path
	Slug string `json:"slug"`
	// Version: Published version the job was exporting
	Version string `json:"version"`
	// Environment: Deployment environment
	Environment Environment `json:"environment"`
	// RenderMode: Render mode of the failed job
	RenderMode RenderMode `json:"renderMode"`
	// ErrorCode: Final classified error code — full PRD 0010 §13 registry. STATUS_CONFLICT and CONFIG_MISSING are listed for registry completeness but do not normally appear in emitted events (409 stops the worker safely without an EXPORT_FAILED transition; CONFIG_MISSING is a boot-time failure before any job starts).
	ErrorCode ErrorCode `json:"errorCode"`
	// ErrorClassification: Retry classification of errorCode per PRD 0010 §13
	ErrorClassification ErrorClassification `json:"errorClassification"`
	// FailedStage: Pipeline stage that failed — trace-span vocabulary of PRD 0010 §15.3
	FailedStage FailedStage `json:"failedStage"`
	// Attempt: Business retry attempt at failure time, 0..3 (PRD 0010 §10.3.1 counting rule; pending-message reclaim never increments this)
	Attempt int64 `json:"attempt"`
	// RetryExhausted: true when a retryable error exhausted maxRetries = 3 (attempt 3) and the job was terminally failed + DLQ-routed
	RetryExhausted bool `json:"retryExhausted"`
	// TraceID: Trace ID of the producing job (cross-boundary traceability, FR-020)
	TraceID string `json:"traceId"`
	// CreatedAt: Emit time, ISO 8601 — field name matches the inbound event vocabulary (PRD 0008 §8.1)
	CreatedAt string `json:"createdAt"`
}
