// Code generated by packages/contracts-codegen/generate.ts from contracts/events/v1. DO NOT EDIT.

package events

// Raw JSON Schema sources (draft 2020-12), embedded so the worker can
// validate payloads offline without a filesystem dependency on the
// platform repo.
const (
	SchemaExportRequested = `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/ancyloce/anvilkit-platform/contracts/events/v1/deployment.export.requested.schema.json",
  "title": "deployment.export.requested",
  "description": "Inbound export request event consumed by anvilkit-export-worker from the queue (Redis Streams stream anvilkit:deployment.export.requested at MVP). Field vocabulary preserves PRD 0008 §8.1 exactly. Event fields renderMode/version/slug are hints only: the worker reconciles them against the authoritative deployment record (FR-004); a mismatch is non-retryable VALIDATION_FAILED. Additive evolution only — removing or renaming a field requires a schema version bump (FR-002). Consumers must tolerate unknown additional properties.",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "eventId",
    "eventType",
    "deploymentId",
    "teamId",
    "siteId",
    "pageId",
    "slug",
    "version",
    "renderMode",
    "targetId",
    "environment",
    "idempotencyKey"
  ],
  "properties": {
    "eventId": {
      "type": "string",
      "minLength": 1,
      "description": "Event ID"
    },
    "eventType": {
      "const": "deployment.export.requested",
      "description": "Always deployment.export.requested"
    },
    "deploymentId": {
      "type": "string",
      "minLength": 1,
      "description": "Deployment record ID — the authoritative idempotency anchor (one deploymentId → at most one artifact manifest)"
    },
    "teamId": {
      "type": "string",
      "minLength": 1,
      "description": "Team ID"
    },
    "siteId": {
      "type": "string",
      "minLength": 1,
      "description": "Site ID"
    },
    "pageId": {
      "type": "string",
      "minLength": 1,
      "description": "Page ID"
    },
    "slug": {
      "type": "string",
      "minLength": 1,
      "description": "Page path"
    },
    "version": {
      "type": "string",
      "minLength": 1,
      "description": "Published version — must be pinned at render (PRD 0008 §12.1 / FR-004)"
    },
    "renderMode": {
      "type": "string",
      "enum": ["fetch_route", "react_ssr", "html_export"],
      "description": "Render mode; fetch_route is the MVP mode, react_ssr and html_export are deferred"
    },
    "targetId": {
      "type": "string",
      "minLength": 1,
      "description": "CDN target ID (passed through to downstream)"
    },
    "environment": {
      "type": "string",
      "enum": ["production", "preview"],
      "description": "Deployment environment"
    },
    "requestedBy": {
      "type": "string",
      "description": "Requesting user, for auditing (optional)"
    },
    "idempotencyKey": {
      "type": "string",
      "minLength": 1,
      "description": "Producer-supplied queue-dedup hint only; the worker derives its own artifact key from deploymentId (PRD 0008 §12)"
    },
    "createdAt": {
      "type": "string",
      "format": "date-time",
      "description": "Emit time, ISO 8601 (optional)"
    }
  }
}
`

	SchemaArtifactReady = `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/ancyloce/anvilkit-platform/contracts/events/v1/deployment.artifact.ready.schema.json",
  "title": "deployment.artifact.ready",
  "description": "Outbound success event emitted by anvilkit-export-worker after the CAS transition to ARTIFACT_READY succeeds (CAS-then-emit, FR-013). Minimum schema per PRD 0010 §10.3.2. routes[] is intentionally omitted (BD-001 / ADR-001): cdn-service reads route data from artifact-manifest.json, where routes[] remains present and always an array (FR-012); routes[] may be added to this event later only as an additive optimization field. Emission is at-least-once — consumers must be duplicate-tolerant keyed by deploymentId. Additive evolution only — removing or renaming a field requires a schema version bump (FR-002).",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schemaVersion",
    "eventId",
    "eventType",
    "deploymentId",
    "teamId",
    "siteId",
    "pageId",
    "slug",
    "version",
    "environment",
    "renderMode",
    "artifactBasePath",
    "manifestStorageKey",
    "manifestDigest",
    "entry",
    "filesCount",
    "totalBytes",
    "traceId",
    "createdAt"
  ],
  "properties": {
    "schemaVersion": {
      "const": 1,
      "description": "Outbound event schema version"
    },
    "eventId": {
      "type": "string",
      "minLength": 1,
      "description": "Event ID"
    },
    "eventType": {
      "const": "deployment.artifact.ready",
      "description": "Always deployment.artifact.ready"
    },
    "deploymentId": {
      "type": "string",
      "minLength": 1,
      "description": "Deployment record ID — consumer dedup key"
    },
    "teamId": {
      "type": "string",
      "minLength": 1,
      "description": "Team ID"
    },
    "siteId": {
      "type": "string",
      "minLength": 1,
      "description": "Site ID"
    },
    "pageId": {
      "type": "string",
      "minLength": 1,
      "description": "Page ID"
    },
    "slug": {
      "type": "string",
      "minLength": 1,
      "description": "Page path"
    },
    "version": {
      "type": "string",
      "minLength": 1,
      "description": "Published version the artifact was rendered from"
    },
    "environment": {
      "type": "string",
      "enum": ["production", "preview"],
      "description": "Deployment environment"
    },
    "renderMode": {
      "type": "string",
      "enum": ["fetch_route", "react_ssr", "html_export"],
      "description": "Render mode used to produce the artifact"
    },
    "artifactBasePath": {
      "type": "string",
      "minLength": 1,
      "description": "Storage base path of the artifact, confined to sites/{siteId}/deployments/{deploymentId} (FR-010)"
    },
    "manifestStorageKey": {
      "type": "string",
      "minLength": 1,
      "description": "Storage key of artifact-manifest.json (internal-only object, never public — FR-012)"
    },
    "manifestDigest": {
      "type": "string",
      "pattern": "^sha256-",
      "description": "SHA-256 digest of the manifest, sha256-<hex> form"
    },
    "entry": {
      "type": "string",
      "minLength": 1,
      "description": "Entry HTML path within the artifact, e.g. /home/index.html"
    },
    "filesCount": {
      "type": "integer",
      "minimum": 0,
      "description": "Number of files in the artifact"
    },
    "totalBytes": {
      "type": "integer",
      "minimum": 0,
      "description": "Total artifact size in bytes"
    },
    "traceId": {
      "type": "string",
      "minLength": 1,
      "description": "Trace ID of the producing job (cross-boundary traceability, FR-020)"
    },
    "createdAt": {
      "type": "string",
      "format": "date-time",
      "description": "Emit time, ISO 8601 — field name matches the inbound event vocabulary (PRD 0008 §8.1)"
    }
  }
}
`

	SchemaExportFailed = `{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/ancyloce/anvilkit-platform/contracts/events/v1/deployment.export.failed.schema.json",
  "title": "deployment.export.failed",
  "description": "Outbound failure event emitted by anvilkit-export-worker after the CAS transition to EXPORT_FAILED (CAS-then-emit, FR-013). Minimum schema per PRD 0010 §10.3.2. errorCode values preserve the PRD 0010 §13 registry exactly (PRD 0008 §12.2 plus the four per-service auth codes); adding a code requires a contracts version note. failedStage reuses the trace-span vocabulary of PRD 0010 §15.3. attempt follows the §10.3.1 counting rule: maxRetries = 3 means attempt values 0..3 (one initial + three retry executions). Emission is at-least-once — consumers must be duplicate-tolerant keyed by deploymentId. Additive evolution only — removing or renaming a field requires a schema version bump (FR-002).",
  "type": "object",
  "additionalProperties": true,
  "required": [
    "schemaVersion",
    "eventId",
    "eventType",
    "deploymentId",
    "teamId",
    "siteId",
    "pageId",
    "slug",
    "version",
    "environment",
    "renderMode",
    "errorCode",
    "errorClassification",
    "failedStage",
    "attempt",
    "retryExhausted",
    "traceId",
    "createdAt"
  ],
  "properties": {
    "schemaVersion": {
      "const": 1,
      "description": "Outbound event schema version"
    },
    "eventId": {
      "type": "string",
      "minLength": 1,
      "description": "Event ID"
    },
    "eventType": {
      "const": "deployment.export.failed",
      "description": "Always deployment.export.failed"
    },
    "deploymentId": {
      "type": "string",
      "minLength": 1,
      "description": "Deployment record ID — consumer dedup key"
    },
    "teamId": {
      "type": "string",
      "minLength": 1,
      "description": "Team ID"
    },
    "siteId": {
      "type": "string",
      "minLength": 1,
      "description": "Site ID"
    },
    "pageId": {
      "type": "string",
      "minLength": 1,
      "description": "Page ID"
    },
    "slug": {
      "type": "string",
      "minLength": 1,
      "description": "Page path"
    },
    "version": {
      "type": "string",
      "minLength": 1,
      "description": "Published version the job was exporting"
    },
    "environment": {
      "type": "string",
      "enum": ["production", "preview"],
      "description": "Deployment environment"
    },
    "renderMode": {
      "type": "string",
      "enum": ["fetch_route", "react_ssr", "html_export"],
      "description": "Render mode of the failed job"
    },
    "errorCode": {
      "type": "string",
      "enum": [
        "VALIDATION_FAILED",
        "PAGE_NOT_FOUND",
        "VERSION_NOT_FOUND",
        "VERSION_SLUG_MISMATCH",
        "PAGE_NOT_PUBLISHED",
        "INVALID_SLUG",
        "ASSET_PERMISSION_DENIED",
        "UNRESOLVED_ASSET_REF",
        "UNSUPPORTED_DYNAMIC_IMAGE_OPTIMIZER",
        "PATH_TRAVERSAL_DETECTED",
        "RENDER_ORIGIN_401",
        "RENDER_ORIGIN_403",
        "RENDER_ORIGIN_404",
        "RENDER_ORIGIN_5XX",
        "RENDER_ORIGIN_TIMEOUT",
        "STORAGE_TIMEOUT",
        "STORAGE_5XX",
        "ARTIFACT_UPLOAD_TIMEOUT",
        "DEPLOYMENT_SERVICE_TIMEOUT",
        "QUEUE_TEMPORARY_FAILURE",
        "STATUS_CONFLICT",
        "CONFIG_MISSING",
        "DEPLOYMENT_SERVICE_401",
        "DEPLOYMENT_SERVICE_403",
        "ASSET_SERVICE_401",
        "ASSET_SERVICE_403"
      ],
      "description": "Final classified error code — full PRD 0010 §13 registry. STATUS_CONFLICT and CONFIG_MISSING are listed for registry completeness but do not normally appear in emitted events (409 stops the worker safely without an EXPORT_FAILED transition; CONFIG_MISSING is a boot-time failure before any job starts)."
    },
    "errorClassification": {
      "type": "string",
      "enum": ["RETRYABLE", "NON_RETRYABLE"],
      "description": "Retry classification of errorCode per PRD 0010 §13"
    },
    "failedStage": {
      "type": "string",
      "enum": [
        "consume_job",
        "load_deployment",
        "acquire_lock",
        "update_status_exporting",
        "render_html",
        "harvest_dependencies",
        "upload_artifacts",
        "write_manifest",
        "submit_artifact",
        "update_status_ready",
        "emit_ready",
        "ack_message"
      ],
      "description": "Pipeline stage that failed — trace-span vocabulary of PRD 0010 §15.3"
    },
    "attempt": {
      "type": "integer",
      "minimum": 0,
      "maximum": 3,
      "description": "Business retry attempt at failure time, 0..3 (PRD 0010 §10.3.1 counting rule; pending-message reclaim never increments this)"
    },
    "retryExhausted": {
      "type": "boolean",
      "description": "true when a retryable error exhausted maxRetries = 3 (attempt 3) and the job was terminally failed + DLQ-routed"
    },
    "traceId": {
      "type": "string",
      "minLength": 1,
      "description": "Trace ID of the producing job (cross-boundary traceability, FR-020)"
    },
    "createdAt": {
      "type": "string",
      "format": "date-time",
      "description": "Emit time, ISO 8601 — field name matches the inbound event vocabulary (PRD 0008 §8.1)"
    }
  }
}
`
)
