// Code generated by packages/contracts-codegen/generate.ts from contracts/openapi/v1/deployment-service.internal.json. DO NOT EDIT.

package deploymentservice

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// Client is a minimal generated client for the deployment-service internal API (consumed contract).
// It owns transport mechanics only. Worker-level concerns — retryable-error
// mapping, timeout budgets, alerting classification — belong to the client
// wrapper tasks (EW-DEPLOY-001 / EW-ARTIFACT-*), not to generated code.
type Client struct {
	// BaseURL is the service base URL, e.g. http://deployment-service:8080.
	BaseURL string
	// Token is the INTERNAL_SERVICE_TOKEN bearer credential (PRD 0010 §11.1).
	Token string
	// HTTPClient is the underlying transport; http.DefaultClient when nil.
	HTTPClient *http.Client
}

// APIError is returned for responses with no operation-specific mapping.
type APIError struct {
	StatusCode int
	Body       []byte
}

func (e *APIError) Error() string {
	body := e.Body
	if len(body) > 512 {
		body = body[:512]
	}
	return fmt.Sprintf("deploymentservice: unexpected status %d: %s", e.StatusCode, string(body))
}

// GetDeployment — Load the authoritative deployment record.
// GET /internal/deployments/{deploymentId}
func (c *Client) GetDeployment(ctx context.Context, deploymentID string) (*DeploymentRecord, error) {
	path := "/internal/deployments/" + url.PathEscape(deploymentID)
	var out DeploymentRecord
	if err := c.do(ctx, "GET", path, nil, &out, nil); err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateDeploymentStatus — Compare-and-set status transition.
// PATCH /internal/deployments/{deploymentId}/status
func (c *Client) UpdateDeploymentStatus(ctx context.Context, deploymentID string, body StatusUpdateRequest) error {
	path := "/internal/deployments/" + url.PathEscape(deploymentID) + "/status"
	return c.do(ctx, "PATCH", path, &body, nil, map[int]func([]byte) error{
		409: func(b []byte) error {
			var e StatusConflictError
			if err := json.Unmarshal(b, &e); err != nil {
				return &APIError{StatusCode: 409, Body: b}
			}
			return &e
		},
	})
}

// SubmitArtifact — Submit the artifact manifest pointer.
// POST /internal/deployments/{deploymentId}/artifact
func (c *Client) SubmitArtifact(ctx context.Context, deploymentID string, body ArtifactPointer) error {
	path := "/internal/deployments/" + url.PathEscape(deploymentID) + "/artifact"
	return c.do(ctx, "POST", path, &body, nil, nil)
}

func (c *Client) do(ctx context.Context, method, path string, in, out any, errHooks map[int]func([]byte) error) error {
	var reqBody io.Reader
	if in != nil {
		buf, err := json.Marshal(in)
		if err != nil {
			return err
		}
		reqBody = bytes.NewReader(buf)
	}
	req, err := http.NewRequestWithContext(ctx, method, strings.TrimRight(c.BaseURL, "/")+path, reqBody)
	if err != nil {
		return err
	}
	if in != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if c.Token != "" {
		req.Header.Set("Authorization", "Bearer "+c.Token)
	}
	hc := c.HTTPClient
	if hc == nil {
		hc = http.DefaultClient
	}
	resp, err := hc.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}
	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if out != nil && len(body) > 0 {
			return json.Unmarshal(body, out)
		}
		return nil
	}
	if hook, ok := errHooks[resp.StatusCode]; ok {
		return hook(body)
	}
	return &APIError{StatusCode: resp.StatusCode, Body: body}
}
