// Code generated by packages/contracts-codegen/generate.ts from contracts/openapi/v1/deployment-service.internal.json. DO NOT EDIT.

// Package deploymentservice contains Go bindings for the deployment-service internal API (consumed contract).
// The OpenAPI document is the contract of record; shapes preserve
// PRD 0008 §8 / PRD 0010 §8 exactly. Generated and committed; platform CI
// regenerates and fails on drift (FR-002).
package deploymentservice

import "fmt"

// DeploymentStatus Full DeploymentStatus enum owned by deployment-service (PRD 0010 §6.3). The worker sets only EXPORTING, ARTIFACT_READY, EXPORT_FAILED via CAS.
type DeploymentStatus string

// DeploymentStatus values.
const (
	DeploymentStatusPending       DeploymentStatus = "PENDING"
	DeploymentStatusExportQueued  DeploymentStatus = "EXPORT_QUEUED"
	DeploymentStatusExporting     DeploymentStatus = "EXPORTING"
	DeploymentStatusArtifactReady DeploymentStatus = "ARTIFACT_READY"
	DeploymentStatusCdnUploading  DeploymentStatus = "CDN_UPLOADING"
	DeploymentStatusCdnPurging    DeploymentStatus = "CDN_PURGING"
	DeploymentStatusVerifying     DeploymentStatus = "VERIFYING"
	DeploymentStatusActive        DeploymentStatus = "ACTIVE"
	DeploymentStatusExportFailed  DeploymentStatus = "EXPORT_FAILED"
	DeploymentStatusCancelled     DeploymentStatus = "CANCELLED"
)

// DeploymentRecord Authoritative deployment record (read shape of PRD 0008 §8.2). The deployment-service owns this data; the worker never reads its database directly.
type DeploymentRecord struct {
	DeploymentID string           `json:"deploymentId"`
	TeamID       string           `json:"teamId"`
	SiteID       string           `json:"siteId"`
	PageID       string           `json:"pageId"`
	Slug         string           `json:"slug"`
	Version      string           `json:"version"`
	Status       DeploymentStatus `json:"status"`
	RenderMode   string           `json:"renderMode"`
	TargetID     string           `json:"targetId"`
	Environment  string           `json:"environment"`
}

// StatusUpdateRequest CAS status transition body (PRD 0008 §8.2 with reason/traceId per report 0010 §10.2). Every transition is audited: deployment-service writes deployment_events.
type StatusUpdateRequest struct {
	From DeploymentStatus `json:"from"`
	To   DeploymentStatus `json:"to"`
	// Reason: Machine-readable transition reason, e.g. worker_started
	Reason  string `json:"reason"`
	TraceID string `json:"traceId"`
}

// StatusConflictError 409 body on CAS mismatch (PRD 0008 §8.2). The worker stops safely; ack only when the deployment is terminal/non-actionable.
type StatusConflictError struct {
	ErrorCode     string           `json:"error"`
	CurrentStatus DeploymentStatus `json:"currentStatus"`
}

// ArtifactPointer Artifact manifest pointer/summary (PRD 0008 §8.2, manifestDigest/entry/routes per D-3). Unlike the deployment.artifact.ready event (ADR-001), this submission DOES carry routes[] — always an array.
type ArtifactPointer struct {
	// ManifestStorageKey: Storage key of artifact-manifest.json
	ManifestStorageKey string `json:"manifestStorageKey"`
	// ArtifactBasePath: Storage base path, confined to sites/{siteId}/deployments/{deploymentId} (FR-010)
	ArtifactBasePath string `json:"artifactBasePath"`
	// ManifestDigest: SHA-256 digest of the manifest
	ManifestDigest string `json:"manifestDigest"`
	// Entry: Entry HTML path, e.g. /home/index.html
	Entry      string `json:"entry"`
	FilesCount int64  `json:"filesCount"`
	TotalBytes int64  `json:"totalBytes"`
	// Routes: Route table — always an array (FR-012 invariant)
	Routes []ArtifactRoute `json:"routes"`
}

// ArtifactRoute One route mapping within the artifact
type ArtifactRoute struct {
	// Path: Public route path, e.g. /home
	Path string `json:"path"`
	// Entry: Artifact-relative entry file, e.g. /home/index.html
	Entry string `json:"entry"`
}

// Error implements the error interface: a decoded StatusConflictError response is
// returned directly as a typed error by the generated client.
func (e *StatusConflictError) Error() string {
	return fmt.Sprintf("deploymentservice: %+v", *e)
}
