// Code generated by packages/contracts-codegen/generate.ts from contracts/openapi/v1/asset-service.internal.json. DO NOT EDIT.

package assetservice

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"strings"
)

// Client is a minimal generated client for the asset-service internal API (consumed contract).
// It owns transport mechanics only. Worker-level concerns — retryable-error
// mapping, timeout budgets, alerting classification — belong to the client
// wrapper tasks (EW-DEPLOY-001 / EW-ARTIFACT-*), not to generated code.
type Client struct {
	// BaseURL is the service base URL, e.g. http://asset-service:8080.
	BaseURL string
	// Token is the INTERNAL_SERVICE_TOKEN bearer credential (PRD 0010 §11.1).
	Token string
	// HTTPClient is the underlying transport; http.DefaultClient when nil.
	HTTPClient *http.Client
}

// APIError is returned for responses with no operation-specific mapping.
type APIError struct {
	StatusCode int
	Body       []byte
}

func (e *APIError) Error() string {
	body := e.Body
	if len(body) > 512 {
		body = body[:512]
	}
	return fmt.Sprintf("assetservice: unexpected status %d: %s", e.StatusCode, string(body))
}

// ResolveAssetsBatch — Resolve a batch of asset:// references.
// POST /internal/assets/resolve-batch
func (c *Client) ResolveAssetsBatch(ctx context.Context, body ResolveBatchRequest) (*ResolveBatchResponse, error) {
	path := "/internal/assets/resolve-batch"
	var out ResolveBatchResponse
	if err := c.do(ctx, "POST", path, &body, &out, nil); err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *Client) do(ctx context.Context, method, path string, in, out any, errHooks map[int]func([]byte) error) error {
	var reqBody io.Reader
	if in != nil {
		buf, err := json.Marshal(in)
		if err != nil {
			return err
		}
		reqBody = bytes.NewReader(buf)
	}
	req, err := http.NewRequestWithContext(ctx, method, strings.TrimRight(c.BaseURL, "/")+path, reqBody)
	if err != nil {
		return err
	}
	if in != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	if c.Token != "" {
		req.Header.Set("Authorization", "Bearer "+c.Token)
	}
	hc := c.HTTPClient
	if hc == nil {
		hc = http.DefaultClient
	}
	resp, err := hc.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}
	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if out != nil && len(body) > 0 {
			return json.Unmarshal(body, out)
		}
		return nil
	}
	if hook, ok := errHooks[resp.StatusCode]; ok {
		return hook(body)
	}
	return &APIError{StatusCode: resp.StatusCode, Body: body}
}
