// Code generated by packages/contracts-codegen/generate.ts from contracts/openapi/v1/asset-service.internal.json. DO NOT EDIT.

// Package assetservice contains Go bindings for the asset-service internal API (consumed contract).
// The OpenAPI document is the contract of record; shapes preserve
// PRD 0008 §8 / PRD 0010 §8 exactly. Generated and committed; platform CI
// regenerates and fails on drift (FR-002).
package assetservice

// ResolveBatchRequest Batch resolve request (PRD 0008 §8.4)
type ResolveBatchRequest struct {
	TeamID string `json:"teamId"`
	SiteID string `json:"siteId"`
	// Refs: asset:// references to resolve
	Refs []string `json:"refs"`
}

// ResolveBatchResponse Batch resolve response (PRD 0008 §8.4)
type ResolveBatchResponse struct {
	Assets []ResolvedAsset `json:"assets"`
}

// ResolvedAsset One resolved asset reference
type ResolvedAsset struct {
	// Ref: The asset:// reference that was resolved
	Ref string `json:"ref"`
	// URL: Resolved URL
	URL       string `json:"url"`
	MimeType  string `json:"mimeType"`
	SizeBytes int64  `json:"sizeBytes"`
	// ContentHash: SHA-256 content hash (never an S3 ETag)
	ContentHash string `json:"contentHash"`
}
