// Code generated by packages/contracts-codegen/generate.ts from contracts/artifact/v1. DO NOT EDIT.

// Package artifact contains Go bindings for artifact-manifest.json —
// the canonical description of one deployment's static artifact bundle
// (PRD 0008 §9.2; FR-012). The manifest is internal-only (private,
// max-age=0, no-store) and routes[] is always an array. The JSON Schema
// file is the contract of record; this package is generated from it.
package artifact

// ManifestFile is one object in the artifact bundle. contentHash matches the object's x-amz-meta-content-sha256 metadata — never an S3 ETag (FR-011).
type ManifestFile struct {
	// Path: Artifact-relative serving path — cdn-service uploads the object to this path at the CDN root (PRD 0008 §9.4)
	Path string `json:"path"`
	// StorageKey: Full storage key under artifactBasePath
	StorageKey string `json:"storageKey"`
	// ContentHash: SHA-256 content hash, sha256-<hex> — matches the object's x-amz-meta-content-sha256 metadata (never an S3 ETag)
	ContentHash string `json:"contentHash"`
	SizeBytes   int64  `json:"sizeBytes"`
	MimeType    string `json:"mimeType"`
	// CacheControl: Per-class cache policy (PRD 0008 §9.3): HTML public, max-age=60, stale-while-revalidate=300 · hashed assets public, max-age=31536000, immutable · non-hashed public, max-age=3600
	CacheControl string `json:"cacheControl"`
}

// ManifestRoute is one route mapping within the artifact.
type ManifestRoute struct {
	// Path: Public route path, e.g. /home
	Path string `json:"path"`
	// Entry: Artifact-relative entry file, e.g. /home/index.html
	Entry string `json:"entry"`
}

// Manifest is artifact-manifest.json (schemaVersion 1).
type Manifest struct {
	// SchemaVersion: Manifest schema version
	SchemaVersion int64  `json:"schemaVersion"`
	DeploymentID  string `json:"deploymentId"`
	SiteID        string `json:"siteId"`
	PageID        string `json:"pageId"`
	Slug          string `json:"slug"`
	// Version: Published version the artifact was rendered from (version-pinned)
	Version     string `json:"version"`
	Environment string `json:"environment"`
	RenderMode  string `json:"renderMode"`
	// ArtifactBasePath: Storage base path — every files[].storageKey lives under it (sites/{siteId}/deployments/{deploymentId}, FR-010)
	ArtifactBasePath string `json:"artifactBasePath"`
	// Entry: Primary route entry, e.g. /home/index.html. For multi-page (P1-001) routes[] is authoritative and entry points at the canonical route.
	Entry string `json:"entry"`
	// Files: Every object in the artifact bundle (the manifest itself is excluded)
	Files []ManifestFile `json:"files"`
	// Routes: Route table — ALWAYS an array (FR-012 invariant); single-page MVP has exactly one entry
	Routes    []ManifestRoute `json:"routes"`
	CreatedAt string          `json:"createdAt"`
}
